######################################################################
# Automatically generated by qmake (3.1) Tue Feb 14 17:53:06 2017
######################################################################

TEMPLATE = app
TARGET = test
INCLUDEPATH += . \
	/usr/local/include \
	../../ \
	../../libdatafile/include

LIBS += -L../lib/ -ldata-source
	
QT += testlib network concurrent
CONFIG += testcase debug
CONFIG -= app_bundle

QMAKE_RPATHDIR += $$(PWD)/../lib $$(PWD)/../../libdatafile/lib

# Input
HEADERS += test-libdata-source.h
SOURCES += test-libdata-source.cc
